version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vibe-coding-postgres
    environment:
      POSTGRES_DB: vibe_coding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - vibe-coding-network

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: vibe-coding-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=vibe_coding
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_ACCESS_TOKEN=${TMDB_ACCESS_TOKEN}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vibe-coding-network
    restart: unless-stopped

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: vibe-coding-frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vibe-coding-network
    restart: unless-stopped

networks:
  vibe-coding-network:
    driver: bridge

volumes:
  postgres_data: